site_name: 智能体大赛引导文档
nav:
  - 文档说明: index.md
  - 平台介绍: platform.md
  - 游戏文档: 
    - Rollman游戏简介: document/pacman.md
    - Rollman通信文档: document/pacman_api.md
  - sdk结构:
    - 总览: sdk_structure/sdk.md
    - 热身赛: sdk_structure/test_race_sdk.md
    - 科研！社工？卷绩人！: sdk_structure/pacman_sdk.md
  - 播放器使用说明:
    - 总览: player/player.md
    - 热身赛: player/test_race.md
    - 科研！社工？卷绩人！: player/pacman.md
  - 开发引导:
    - 热身赛: instruction/test_race.md
    - 科研！社工？卷绩人！: instruction/pacman.md
  - 讲座资料:
    - 科研！社工？卷绩人！: 
      - 视频链接: lecture/pacman.md
      - 算法入门: lecture/algorithms.pdf
theme:
  logo: imgs/icon.jpg
  favicon: imgs/icon.jpg
  palette:
    primary: black
  name: material

markdown_extensions: 
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.pathconverter:
      base_path: 'agent_guide' # default: ''
      relative_path: '' # default ''
      absolute: true # default: false
      tags: 'a script img link object embed'

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - javascripts/katex.js
  - https://unpkg.com/browse/katex@0.16.11/dist/katex.min.js
  - https://unpkg.com/browse/katex@0.16.11/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/browse/katex@0.16.11/dist/katex.min.css

plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      fallback_to_build_date: true
      locale: zh
  - git-authors:
      show_contribution: true
      show_line_count: true